### ISSUE TITLE
`integer` 字段需要指定长度

### ISSUE THREAD

**Issue by ilharp** [Lipraty/koishi-plugin-sleep-manage#2]
![image](https://user-images.githubusercontent.com/20179549/212147157-827dde1f-ba1c-4fd3-b0d2-d3dd8deab8f1.png)

参考 [文档](https://koishi.chat/api/database/model.html#%E6%95%B0%E5%80%BC%E7%B1%BB%E5%9E%8B)，默认长度为 10，不够 timestamp 用的，需要 13 位

**Comment by Lipraty** [comment]
好的，会在下个版本（
